# Generated by Django 4.2.5 on 2023-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0002_page_article_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
