# Generated by Django 4.2.5 on 2023-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0003_page_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='edit_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
