# Generated by Django 4.2.5 on 2023-09-29 15:42

from django.db import migrations, models
from CoolSchool import settings


def forward_func(apps, schema_editor):
    Page = apps.get_model('articles_app', 'Page')
    default_pages = settings.DEFAULT_PAGES
    for title in default_pages.keys():
        Page.objects.get_or_create(title=title, page_url=default_pages[title]['url'], edit_url=default_pages[title]['edit_url'])


def reverse_func(apps, schema_editor):
    Page = apps.get_model('articles_app', 'Page')
    default_pages = settings.DEFAULT_PAGES
    for title in default_pages.keys():
        Page.objects.filter(title=title).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('articles_app', '0004_page_edit_url'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
