# Generated by Django 4.2.5 on 2024-01-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_on_whiteboard',
            field=models.BooleanField(default=False),
        ),
    ]
